import React from "react"
/**
 *
 * -Elizabeth K. 12/23/2019
 * - Shana C 10/6/2019
 * 11/26/2018 by Ben T
 * 10/21/2018 by Morgan L
 */

function Reviews(props){
  return (
    <>
      <h3>
        <u>
          See what past couples have said
        </u>
      </h3>
      <p><i>This band was truly what a 5 star review is made of, they were "The best ever" I cannot describe the energy, talent, and absolutely incredible music that Blue Avenue Groove brought to our wedding day."</i></p>
      <p>-Melissa M</p>
      <p><i>My wife & I can't recommend Blue Avenue Groove highly enough! Seriously, our wedding would not have been the same without them. From funk, to r & b, to the instrumental jazz standards they played during cocktail hour, they can do it all. We had many wedding guests both during and after the reception, tell us that they are by far the best wedding band they'd ever heard, and I wholeheartedly agree. Thank you to Will and the rest of the group for being incredibly talented and kind souls, and for providing us and our guests truly unforgettable music on our big day. I highly recommend booking this amazing group of musicians for any event!</i></p>
      <p>-Ryan B.</p>
      <p><i>This band was the highlight of the wedding for our guests...of all the cover bands I've ever heard, these guys have the strongest musicianship and knack for reading their crowd!</i></p>
      <p>-Morgan L</p>
      <p><i>I cannot recommend Blue Avenue Groove enough! They were amazing! My husband and I got married in November and a month later everyone we see is still telling us how great the band was. The thing I hear most often is "they are not a typical wedding band" and trust me, that is a compliment. They bring a unique and refreshing vibe to the whole wedding and they read the crowd, and had everyone dancing from our three year old nephew to grandparents. In addition to the excellent performance at the wedding, the planning and communication with Will was easy and stress free. Will is quick to reply and listens to your question, requests and details. Do yourself and your guests a favor and book Blue Avenue Groove. You will not be disappointed!</i></p>
      <p>-Elizabeth K.</p>
      <p><i>We cannot recommend Blue Avenue Groove enough. Our guests cannot stop talking about this band and our friends already want to book them at their next wedding! Will was helpful and professional throughout the entire process. More importantly, the vocalists & instrumentalists were out of this world. They played Motown for our wedding but also threw in some unexpected hits that people loved - Whitney Houston and even Queen. They also played our ceremony and were able to learn all of the classical pieces. We loved having them at our wedding and wish that we could do it all again!</i></p>
      <p>-Shana C.</p>
      <p><i>I can't recommend Blue Avenue Groove highly enough... there is not one person in our 110 guests who didn't rave about the band. And I mean RAVE! We chose the 8 piece band, and their song list was absolutely perfect for us. We had everyone from 3 year olds and 80 year olds dancing all night to Reggae, funk, pop and R&B spanning the 60's through today. Ultimately, we chose Blue Avenue Groove because as we were making the decisions about music for our reception, they gave us the kind of attention the larger corporate companies just can't provide. We had no idea they were as good as they turned out to be... Do yourselves a favor and book em before they book your date. If they book your date, it's worth changing your date...assuming they're still available on the alternate </i></p>
      <p>-Ben T</p>
      <p><i>This band was the highlight of the wedding for our guests. First of all, of all the cover bands I’ve ever heard, these guys have the strongest musicianship and really has a knack for reading their crowd. Live music was very important for my husband and I, so we searched long and hard for the “right” vibe that didn’t feel cheesy or too corporate. Blue Ave had the perfect mix of funk, soul, and just downright killer musical talent. My dad is a drummer and the band allowed him to sit in on two songs which was truly a gift not only to him, but to me. Sami Stevens was on lead vocals and literally all weekend, all of our guests kept asking “where in the world did you find that girl? Her voice is unbelievable!!?” I honestly cannot say enough good things about each and every member of the band. We had the best night ever and our friends and family were not only impressed, but thoroughly enjoyed themselves. I saw family members dancing that I’ve never seen on the dance floor before...that’s how you know it was an overwhelming success! Thank you x10000 to Alison (sax player) for coordinating everything and keeping us excited throughout the planning process. If we had it to do all over again, we would book this band every single time. Money well spent...but a priceless experience.</i></p>
      <p>-Morgan L</p>
      <p><i>Will and his band were an absolute BLAST at the wedding! They're extremely talented and sing with soul. We fell in love with them at a friend's wedding and knew we absolutely had to have them at ours. Will was very responsive throughout the entire process (even when abroad) and was a pleasure to work with. They performed with such energy that kept everyone dancing on the dance floor all day. We were super happy with them and highly recommend for any wedding or event!</i></p>
      <p>-Karen H</p>
      <p><i>My daughter and her (now) husband are professional musicians, and half of the guests at their wedding would be serious musicians, so it was important to get a first-rate band -- which Blue Avenue Groove was, and more. They were -- by far -- the best band I have ever heard at a wedding. More than being excellent musicians, they energized the whole crowd, which ranged from a five-year old, who could not stop dancing, to post-70s folks, who had not danced in years. People have been telling us ever since the wedding what a great band Blue Avenue Groove is. Do yourself a favor and hire them.</i></p>
      <p>-Aly P.</p>
      <p><i>Five stars are too few for a band as talented as Blue Avenue Groove!! Their music was the highlight of our wedding and booking them was the best decision we made. We had a lot of trouble finding a band that was willing to stray a little bit from the classic wedding tunes - that is, a band capable of prioritizing rock music, without sacrificing a healthy mix of pop, funk, and Motown. We had almost given up hope, until a friend recommended Blue Avenue Groove. Immediately after speaking with their band leader (and talented bass guitarist), Will Kencel, we knew we found what we were looking for! From the beginning, the band was incredibly flexible and easy to work with. They offered a range of ensemble sizes and options. We ended up booking an eight-piece band (including male and female singers) for the reception and a trio for the cocktail hour, and the price was beyond reasonable for what we received in return. Will was incredibly receptive to learning multiple special requests, and even emailed us a preliminary setlist to tweak and edit. Our guests were blown away by their sound and their style, especially their amazing singers, and the feedback was universally positive. The band’s energy kept people dancing all night - no one wanted to miss a song! If you’re reading this, stop what you’re doing and book Blue Avenue Groove for your wedding!! You will be forever happy with your decision. Don’t delay! The soundtrack to your big day will be exactly as you envision it. We cannot thank them enough!!!</i></p>
      <p>-Kathleen M.</p>
      <p><i>I can't say enough about Blue Avenue Groove. They were AMAZING! Our family and friends cannot stop raving about the music at our wedding. My husband and I are music aficionados and Blue Avenue Groove knocked it out of the park. We booked them for the cocktail hour, reception and ceremony for our 90 guests wedding in Brooklyn. They even accommodated our song requests, which of course were some of the most challenging pieces of music ever written. Blue Avenue Groove outperformed bands that cost twice as much, and gave us a really personalized and unique musical experience. Highly recommended!</i></p>
      <p>-Darryl H.</p>
      <p><i>We can't say enough about Blue Avenue Groove. The group played our Wedding in July and it was a great event. Our guests couldn't stop talking about the band and most came up to us afterwards to tell us how much they enjoyed the music. The group is made up of outstanding musicians, their two lead singers Jonathan and Sami are nothing short of amazing, and they really groove. Will was great to work with, he was all over the the event details- ran by set lists ahead of time with us to craft a great lineup of soul/funk/R&B classics with a few newer tunes thrown in, and was happy to have my husband (a drummer) sit in for a number of songs which delighted the crowd! If you book Blue Avenue Groove for your Wedding you won't be disappointed. </i></p>
      <p>-Adina W.</p>
      <p><i>I hired Blue Avenue Group for my wedding in NYC. They were really amazing. They played a great mix of jazz, instrumental for the cocktail hour and then some really great rock, top 40 and motown numbers when the dancing really took off. Numerous people complemented me on the band and they were asked repeatedly for encores. Great band. Could not recommend them more.</i></p>
      <p>-Ratna G.</p>
      <p><i>Blue Avenue Groove just played at our wedding in Long Island City and did a fantastic job. They were very easy to work with, were able to play our requests super well, and everyone kept asking where we had found them! We had Sami as our vocalist and she was awesome, could really belt it out!</i></p>
      <p>-Haley</p>
      <p><i>Excellent band to hire. Really helped in making the event a success. I highly recommend them for anyone looking for a Motown band that has a versatile repertoire and a great attitude/show.</i></p>
      <p>-John M.</p>
      <p><i>Blue Avenue Groove was terrific! They played a birthday party of 40 people for us, and the whole party loved them. We asked them to play mostly motown, and they were great. I'd love to have a chance to hear more of their current songs too. Will was really easy to work with and made the whole process easy and fun. Highly recommend!!</i></p>
      <p>-Rachel B.</p>
      <p><i>We booked Blue Avenue Groove for our Met Museum Staff Holiday Party and they did not disappoint! They are talented, high-energy, and Will was a pleasure to work with throughout the planning of the event. Highly recommend! </i></p>
      <p>-Leah M.</p>
      <p><i>We were extremely happy that we hired Blue Avenue Groove as our wedding band. First, the wedding involved a number of logistical complications, including multiple transitions between different locations for cocktails, dinner, and dancing, some special requests on the first dance song, and my band using their equipment to play a couple of songs. They handled all of these logistics smoothly so we didn't have to worry about anything.  And then second, they put on a fantastic show, especially wowing the crowd with some funk power and a singer than can really wail. Everybody loved it, and it was just what we were looking for.</i></p>
      <p>-Jesse E.</p>
      <p><i>My daughter and her (now) husband are professional musicians, and half of the guests at their wedding would be serious musicians, so it was important to get a first-rate band -- which Blue Avenue Groove was, and more. They were -- by far -- the best band I have ever heard at a wedding. More than being excellent musicians, they energized the whole crowd, which ranged from a five-year old, who could not stop dancing, to post-70s folks, who had not danced in years. People have been telling us ever since the wedding what a great band Blue Avenue Groove is. Do yourself a favor and hire them</i></p>
      <p>-Marianne</p>
      <p><i>Blue Avenue Groove was truly one of the best parts of our wedding. I don't think I've ever attended a wedding where people were more motivated to dance, and that's all thanks to Blue Avenue Groove's incredible musicianship, emceeing flair, and true professionalism. My husband and I are both musicians, and were getting really disheartened by how many wedding bands seemed like bad karaoke outfits. We could tell from Blue Avenue Groove's demos that they were really making all these classic songs their own - while still making them extremely danceable, and we couldn't be happier that we hired them. Will was extremely accommodating and flexible with our requests, from agreeing to play a song with my dad sitting in on guitar to switching the father-daughter song last-minute when my dad broke his wrist. Will and the sound technician (Billy, I think) also helped accommodate a late request from me to perform with one of my bridesmaids, and seamlessly set up microphones for us to play cello and sing in the middle of the reception. Every single musician on stage was top-notch, and the singers did an especially great job guiding the flow of the reception and making all the transitions super-organic! They're also incredibly reasonable as far as bands go, and in my opinion worth far more than they charge. At least 50 or so of our guests were professional musicians, and every one of them (as well as the non-musicians in the crowd) commented on how amazing the band was - I only wish we could get married again so we could have another Blue Avenue Groove dance party!</i></p>
      <p>-Meaghan</p>
      <p><i>Five stars are too few for a band as talented as Blue Avenue Groove!! Their music was the highlight of our wedding and booking them was the best decision we made. We had a lot of trouble finding a band that was willing to stray a little bit from the classic wedding tunes - that is, a band capable of prioritizing rock music, without sacrificing a healthy mix of pop, funk, and Motown. We had almost given up hope, until a friend recommended Blue Avenue Groove. Immediately after speaking with their band leader (and talented bass guitarist), Will Kencel, we knew we found what we were looking for! From the beginning, the band was incredibly flexible and easy to work with. They offered a range of ensemble sizes and options. We ended up booking an eight-piece band (including male and female singers) for the reception and a trio for the cocktail hour, and the price was beyond reasonable for what we received in return. Will was incredibly receptive to learning multiple special requests, and even emailed us a preliminary setlist to tweak and edit. Our guests were blown away by their sound and their style, especially their amazing singers, and the feedback was universally positive. The band’s energy kept people dancing all night - no one wanted to miss a song!  If you’re reading this, stop what you’re doing and book Blue Avenue Groove for your wedding!! You will be forever happy with your decision. Don’t delay! The soundtrack to your big day will be exactly as you envision it. We cannot thank them enough!!!</i></p>
      <p>-Kathleen</p>
      <p><i>I contacted Blue Avenue Groove after hearing their promo video, which really showcased their musicianship and made them stand out among other similar bands. The bandleader Will was always prompt in his emails back to me, and was kind enough to fix any last-minute snafus (one singer was suddenly unable to perform, so he magicked a new one and sent me her promo video as well). All in all, the band were very friendly and brought some serious funk and energy to the night. I have gotten dozens of compliments from guests about their setlist and talent!  This band has the flexibility to perform in multiple ensemble sizes (ie, horns vs. no horns) and has a full setlist plus a giant list of replacement songs. The pricing structure is very reasonable (please note my price includes the full 8-piece band plus a sound engineer), and any fees are easily described via a conversation with Will.  I'm so happy I booked Blue Avenue Groove--they kept us dancing all night! Well done everyone!</i></p>
      <p>-Emma</p>
      <p><i>Every single member of this band is extremely talented. Super versatile. They have a great ability to keep the energy of any event high. Highlight of our wedding</i></p>
      <p>-Aaron</p>
      <p><i>Choosing the right band for you from a different country is a huge challenge, but when we found Blue Avenue Groove we knew right away that they had the sound we were looking for. Our wedding was a cocktail style reception and our musical taste was laid back, groovy and something that our guests could tap their feet to, moving into something they could dance to if they wanted. Blue Avenue Groove blew us away!!!! I do not mean that lightly - they were absolutely outstanding! All our guests loved them - we have received so many compliments on our choice of band.  Lead by Will, the Band Manager, his passion for what he does is so clear and I think this is what makes him brilliant. Sami was our vocalist and her voice is like velvet! The guitarist was fantastic - his riffs had everyone cheering! The drummer was fabulous! The whole band really made our wedding incredibly fun.  Thanks so much Blue Avenue Groove - we can't recommend you highly enough!!</i></p>
      <p>-Heidi</p>
      <p><i>We can't say enough about Blue Avenue Groove. The group played our Wedding in July and it was a great event. Our guests couldn't stop talking about the band and most came up to us afterwards to tell us how much they enjoyed the music. The group is made up of outstanding musicians, their two lead singers Jonathan and Sami are nothing short of amazing, and they really groove. Will was great to work with, he was all over the the event details- ran by set lists ahead of time with us to craft a great lineup of soul/funk/R&B classics with a few newer tunes thrown in, and was happy to have my husband (a drummer) sit in for a number of songs which delighted the crowd! If you book Blue Avenue Groove for your Wedding you won't be disappointed.</i></p>
      <p>-Adina</p>
      <p><i>My wife & I can't recommend Blue Avenue Groove highly enough! From the time that we booked them, Will and the rest of the band were responsive, personable and flexible with our requests. Not to mention their incredible talent as musicians!!! Seriously, our wedding would not have been the same without them. From funk, to r & b, to the instrumental jazz standards they played during cocktail hour, they can do it all. We had many wedding guests both during and after the reception, tell us that they are by far the best wedding band they'd ever heard, and I wholeheartedly agree. If you want to have all of your wedding guests up out of their seats dancing to the funkiest band in all the land, then hire these guys! Thank you to Will and the rest of the group for being incredibly talented and kind souls, and for providing us and our guests truly unforgettable music on our big day.</i></p>
      <p>-Ryan</p>
      <p><i>I recently booked this group for a party and everyone, to a person, loved them. There were some serious musicians among the guests, who were impressed with the level of the band's ability. The singer, Jon, was fabulous and really got the crowd involved. The most impressive feature was that the band seemed to enjoy the party as much as the guests.  I would highly recommend them and would definitely hire them for my next event.</i></p>
      <p>-Lois</p>
      <p><i>We were so happy with Blue Avenue Groove for our wedding at the Brooklyn Winery. They sound absolutely fantastic and had people of all ages dancing the night away. They were professional and courteous and it was clear that not only did they enjoy what they were doing but also were interested in making the night as special as possible. If I am ever looking for a band for another special event, they will be my first call.</i></p>
      <p>-Sandor</p>
      <p><i>We can't say enough about Blue Avenue Groove. The group played our Wedding in July and it was a great event. Our guests couldn't stop talking about the band and most came up to us afterwards to tell us how much they enjoyed the music. The group is made up of outstanding musicians, their two lead singers Jonathan and Sami are nothing short of amazing, and they really groove. Will was great to work with, he was all over the the event details- ran by set lists ahead of time with us to craft a great lineup of soul/funk/R&B classics with a few newer tunes thrown in, and was happy to have my husband (a drummer) sit in for a number of songs which delighted the crowd! If you book Blue Avenue Groove for your Wedding you won't be disappointed.</i></p>
      <p>-Scott</p>
      <p><i>Absolutely incredible! I cannot say enough good things about Blue Avenue Groove. Each band member was so talented and sounded incredible. Many of my wedding guests who are trained musicians said it was the best wedding band they ever heard. Will was exceptional to work with and really took the time to understand our taste and preferences, and made excellent recommendations as well. They are top notch in every way!</i></p>
      <p>Meredith W.</p>
      <p><i>What I love about Blue Avenue Groove is that they let their high level of musicianship speak for itself. Whereas other bands often compensate for average musicianship by doing over-the-top antics that provide lots of "show", these guys are truly badass musicians, to the point that they don't need to force things - the music carries the day (and they look good doing it too). We heard feedback from countless guests, saying that it was far and away the best wedding band they had ever heard. They also went above and beyond the call of duty, accommodating a very last minute request for "All I Want For Christmas is You", by learning and rehearsing it on their drive down to VA from NYC. The three singers Jon, Sami, and Leah are off the charts! We couldn't have been happier with our choice to hire Blue Avenue Groove.</i></p>
      <p>-Jonah K.</p>
      <p><i>Will and Blue Avenue Groove were everything and more! From the day we sent an inquiry up until the day of our wedding, Will was extremely responsive and super helpful. My husband and I are both musicians, so having a great band for our wedding was a top priority. Blue Avenue Groove delivered 10000000%!!! They made our wedding day so much more special and we are so grateful for that. Our guests said they were the best band they’ve seen at a wedding and they truly are. Amazing amazing stuff! Definitely book them for your wedding, you will not regret it. I just want to go back!!!</i></p>
      <p>-Sarah G.</p>
      <p><i>Music is a huge part of our family's life, and actually was my husband's major in college, so we knew having an epic band was a must at our wedding. While looking online, the minute we found Blue Avenue Groove, we knew the search was over. Every member is an exceptional professional musician who will make your night even more memorable then you can imagine. It seriously felt like we had our own personal concert! They played for our ceremony, cocktail hour, dinner and of course reception. While we couldn't stop dancing, at times we just wanted to stand there and listen to their awesome talent. Will was so easy to work with and knowing the caliber of his team we just picked our 3 personal songs, named our genre of music and left them to do the rest. We didn't even want to see the set list before the wedding because we trusted him completely to own the night and he did!  Save your time, stop looking and book this band. They will exceed all your expectations.</i></p>
      <p>-Jessica F</p>
      <p><i>We absolutely loved having Blue Avenue Groove play our ceremony, cocktail reception, and reception. They were amazing and helped us think through every detail. They learned all of the music that we needed them to, were professional and most importantly - kept the crowd dancing! They even mixed in some songs that we weren't expecting but that the crowd loved. A+ all around -- we wish that we were getting married again this weekend so that we could hear Blue Avenue Groove play again!</i></p>
      <p>-Shana</p>
      <p><i>My husband and I wanted our wedding day to feel like the best party ever, and Blue Avenue Groove made that happen for us. We knew they would be a great addition to our wedding, but we were totally floored by the standard to which they performed. They provided a jazzy saxophone and keyboard duo for cocktail hour, then an 8 piece band for the reception. Don't skimp on the brass! Jon and Sami's vocals blew everyone away and got the party started! We received so many compliments and inquiries from our guests, wondering who these talented, beautiful musicians were and where we found them. Thank you to Will and the band for bringing funk, soul and fun to our wedding day!</i></p>
      <p>-Erica</p>
      <p><i>Blue avenue groove played our summer camp wedding, and boy did they bring the party! EVERYONE was up dancing, and many guests came up to me specifically to remark on how great the band was. They are extremely talented people and they sounded amazing. They also were very helpful and flexible when, during the reception, we found out we had given the caterers and the band different schedules and conflicting information. They communicated really well with my groom and I, and everything went smoothly despite our mistake. 100% recommend them.</i></p>
      <p>-Astrid V.</p>
      <p><i>Can’t say enough amazing things about Blue Avenue Groove. Will and his band were absolutely amazing and we got a ton of compliments from our guests. At one point I even noticed the bartenders watching, and one pulled me aside saying they were the best band they’ve ever had at the venue! They were an absolute pleasure to work with and I’d recommend them to anyone looking to knock their wedding out of the park. True professionals in every sense of the word.</i></p>
      <p>-Jordan S.</p>
      <p><i>"Where did you find your band?!"  That will be the refrain after your wedding if you go with Will and Blue Avenue Groove. I know, because that is all my wife and I have been hearing from our guests. Blue Avenue Groove were consummate professionals, easy to work with, and extremely talented to boot. They had the whole party rocking, and everyone danced their socks off. I honestly cannot recommend them more. We have a friend who is getting married next year, and they have already reached out to get Blue Avenue Groove's contact information because they loved them so much. Make your life easy; just pick Blue Avenue Groove to be your band and enjoy the party! Thank you so much to Will and his team of incredibly talented performers!</i></p>
      <p>-Peter W.</p>
      <br/>
      <h3>
        <u>
          Check out more reviews:
        </u>
      </h3>
      <a href="https://www.weddingwire.com/reviews/blue-avenue-groove-brooklyn/0da4ea28bbbcfffe.html"><button>On Wedding Wire</button></a>
      <br/>
      <br/>
      <a href="https://www.theknot.com/marketplace/blue-avenue-groove-brooklyn-ny-964870"><button>On The Knot</button></a>
    </>
  )
}


export default Reviews